[mitm]
hostname = tapi.zeehoev.com
[rewrite_local]
^https:\/\/tapi\.zeehoev\.com\/v1\.0\/mine\/cfmotoservermine\/setting url script-response-body https://cdn.jsdelivr.net/gh/yuey818/qx-scripts@main/script/zeeho/zeeho.js
